### ISSUE TITLE
[Issue with autovec.py]

### ISSUE THREAD

**Issue by vinayak618** [ucb-bar/NeuroVectorizer#1]
Hi Team,

First of all thank you so much for the open implementation.
Read paper from NEURIPS'19 ML for systems workshop. The result looks very promising. I was trying to replicate the results from paper using this repo. I cloned the github repo and followed the steps as mentioned in the ReadMe document. I'm done with configure.sh and preprocess.sh, **when i run python autovec.py**, i get the below error.

`Error: ModuleNotFoundError: No module named 'my_model'.`

Note: I know it is present inside code2vec directory and i'm running the code from repo home directory. please help me resolve the issue or else i would take more time to change it manually for all files.

Thanks and Regards,
Vinayak N Baddi

**Comment by AmeerHajAli** [comment]
Hi Vinayak,
Thanks for reporting this issue. 
Try adding the path to code2vec directory in your PYTHONPATH environment variable.
