### ISSUE TITLE
related to rollout

### ISSUE THREAD

**Issue by TimHuDi** [ucb-bar/NeuroVectorizer#11]
Hi @AmeerHajAli:
       I find the rollout result is non-deterministic for the same code. That is to say, if I run the rollout multiple times, the generated VF and IF could be different for the same code. There is any way to make the rollout deterministic?

Best Regards
TimHu

**Comment by AmeerHajAli** [comment]
Hi @TimHuDi , This is related to how ray works as it is stochastic (you sample from a distribution). You can make it deterministic by setting the seed (see https://ray.readthedocs.io/).

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
    Thanks for your sharing, It works.
Best  Regards
TimHu
