### ISSUE TITLE
Is there any code about generating the results of MiBench and PolyBench as shown in figs. 10 and 11 of the paper? 

### ISSUE THREAD

**Issue by gloaming2dawn** [ucb-bar/NeuroVectorizer#13]
As shown in Figs.10 and 11 of the paper "NeuroVectorizer: End-to-End Vectorization with Deep
Reinforcement Learning", could you provide source codes about generating the results of MiBench and PolyBench?

**Comment by AmeerHajAli** [comment]
Hi @gloaming2dawn , thanks for asking.
Can you try  using the artifact description in the paper?
https://dl.acm.org/doi/pdf/10.1145/3368826.3377928

**Comment by gloaming2dawn** [comment]
Hi, @AmeerHajAli , Fig.9 can be reproduced as the artifact description. However, there is no artifact description about the result of PolyBench (i.e., fig. 10). When I try to reproduce the result of PolyBench, I cannot get the similar result of fig. 10. Pragmas are invalid for many loops in PolyBench (shown "loop not vectorized" when compiling).

**Comment by AmeerHajAli** [comment]
Can you please provide more details on how are you running it and which version of LLVM are your running?
